# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Humble Software notes
tagline:             'by Achilleas Kalkatzakos'
url:                 http://akalkatzakos.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Achilleas Kalkatzakos
  url:               
  email:             akalkatzakos@gmail.com

# Custom vars
version:             1.0.0
